environment:
        - target: msvc
        - ver: 15
        - generator: "Visual Studio 15 2017 Win64"
        - configuration: Release
platform:
        - x64
build_script:
        - mkdir build_win &&
        - cd build_win &&
        - cmake -G "Visual Studio 15 Win64" ../ &&
        - MSBuild xLearn.sln
