image: Visual Studio 2017
build_script:
        mkdir build_win &&
        cd build_win &&
        cmake -G "Visual Studio 15 Win64" ../ &&
        MSBuild xLearn.sln &&
        cd python-package && ^
        python setup.py bdist_wheel
test_script:
        cd test &&
        run_all_test.bat
artifacts:
        path: **\*.whl
        name: Bits
