image: Visual Studio 2017
build_script:
        mkdir build_win &&
        cd build_win &&
        cmake -G "Visual Studio 15 Win64" ../ &&
        MSBuild xLearn.sln /p:Configuration=Release &&
        cd python-package &&
        C:\\Python36-x64\\Scripts\\pip install wheel numpy scipy scikit-learn cython &&
        C:\\Python36-x64\\python.exe setup.py bdist_wheel
test_script:
        cd test &&
        .\\base\\Release\\file_util_test.exe &&
        .\\base\\Release\\levenshtein_distance_test.exe &&
        .\\base\\Release\\thread_pool_test.exe &&
        .\\c_api\\Release\\c_api_test.exe &&
        .\\data\\Release\\data_structure_test.exe &&
        .\\data\\Release\\model_parameters_test.exe &&
        .\\loss\\Release\\cross_entropy_loss_test.exe &&
        .\\loss\\Release\\loss_test.exe &&
        .\\loss\\Release\\metric_test.exe &&
        .\\loss\\Release\\squared_loss_test.exe &&
        .\\reader\\Release\\file_splitor_test.exe &&
        .\\reader\\Release\\parser_test.exe &&
        .\\reader\\Release\\reader_test.exe &&
        .\\score\\Release\\ffm_score_test.exe &&
        .\\score\\Release\\fm_score_test.exe &&
        .\\score\\Release\\linear_score_test.exe &&
        .\\score\\Release\\score_function_test.exe
artifacts:
        path: python-package\\dist\\*.whl
        name: Bits
