image: Visual Studio 2017
build_script:
        mkdir build_win &&
        cd build_win &&
        cmake -G "Visual Studio 15 Win64" ../ &&
        MSBuild xLearn.sln /p:Configuration=Release &&
        cd python-package &&
        C:\\Python36-x64\\Scripts\\pip install wheel numpy scipy scikit-learn cython &&
        C:\\Python36-x64\\python.exe setup.py bdist_wheel
artifacts:
        path: build_win\python-package\dist\*.whl
        name: Bits
